<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>23.3</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="e383efd0-a8de-4292-9c1c-def6506ab87d" Name="DESKTOP-0E3NN5N" System="IRB140_6_81" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 23.2.10395.0</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.13.4007</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>Interfaz App</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>0</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="A1" Value="1" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="A2" Value="2" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="A3" Value="3" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="B1" Value="4" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="B2" Value="5" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="B3" Value="6" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="time" Value="100" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MainScreen.view">
			<Link>MainScreen.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.13.4007</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>